### ISSUE TITLE
Server accepts empty flights POST

### ISSUE THREAD

**Issue by CaffeinatedAndroid** [wquist/Goshna#2]
Server accepts (HTTP 201) an empty flight submission from the app. Though no new flight info is created server-side.

Server should not accept empty POST request and return a suitable error code.

**Comment by wquist** [comment]
Commit 06548ff519358ee68f39fa5050601fc22e94dc85 should prevent this from happening now - the callbacks will verify that none of the JSON fields are empty strings.

However, tables that take maintain IDs in their columns are still susceptible; a bad POST could create a Flight with a bad `airline_id`, for example. The server should check if the passed IDs are valid in the relevant tables.

**Comment by CaffeinatedAndroid** [comment]
Great - create a new Issue about the "bad POSTs", then you can close this one.
