### ISSUE TITLE
Passenger app: Announcements activity should have gate number pinned to top.

### ISSUE THREAD

**Issue by CaffeinatedAndroid** [wquist/Goshna#4]
When viewing the announcements list in the passenger app, showing the gate number at the top of the Activity could reassure the user the announcements are for their flight. Could also show limited flight details of the "Next Flight". When looking at an empty Activity (before any announcements have been made), it's possible that users may press 'Back' to double-check they have selected the correct flight.

**Comment by wquist** [comment]
Commit 42e67e4422c2e627a1fb5e8bddc645331852f28f displays the gate number along with the flight name.
